FROM fedora:latest AS base
RUN dnf install -y httpd && dnf clean all
EXPOSE 80
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]

FROM baseline AS website1 
COPY website1.html /var/www/html/index.html
LABEL website="1"

FROM baseline AS website2 
COPY website2.html /var/www/html/index.html
LABEL website="2"