FROM fedora:latest AS base
RUN dnf -y install httpd && \
    mkdir -p /var/www/html
EXPOSE 80
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]

#for website1 stage
FROM base AS website1 
COPY website1.html /var/www/html/index.html
LABEL website="1"
#For website2 stage
FROM base AS website2 
COPY website2.html /var/www/html/index.html
LABEL website="2"
#Final image for website1
FROM website1 AS final
LABEL final="website1"